blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name= 'home'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('proyectodjango/', include('proyectodjango.urls', namespace='proyectodjango'))
]

proyectodjango/urls.py
from django.urls import path

from proyectodjango.views import ProyectoDjangoIndex

app_name = 'proyectodjango'

urlpatterns = [
    path('', ProyectoDjangoIndex.as_view(), name='home')
]

blog/models.py
from email.policy import default
from pyexpat import model
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length = 200)
    content = models.TextField(default='')
    
    def __str__(self):
        return self.title
    

proyectodjango/models.py
from django.db import models

# Create your models here.

blog/forms.py
from dataclasses import fields
import imp
from django import forms 
from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post 
        fields = ('title', 'content')

blog/views.py
from multiprocessing import context
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, UpdateView, DeleteView
from django.urls import reverse_lazy


from blog.forms import PostCreateForm
from blog.models import Post

# Create your views here.

class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts=Post.objects.all()
        context={
            'posts' : posts
        }
        return render(request, 'blog_list.html', context)

class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form = PostCreateForm()
        context = {
            'form':form 
            }
        return render(request, 'blog_create.html', context)

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')

                p, created = Post.objects.get_or_create(title=title, content=content)
                p.save
                return redirect('blog:home')
            context = {}

class BlogDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        context = {
            'post':post
        }
        return render(request, 'blog_detail.html', context)

class BlogUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content']
    template_name = 'blog_update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk':pk})


class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'blog_delete.html'
    success_url = reverse_lazy('blog:home')

core/views.py
from django.shortcuts import render
from django.views.generic import View

# Create your views here.

class HomeView(View):
    def get(self, request, *args, **kwargs):
        context={}
        return render(request, 'index.html', context)

proyectodjango/views.py
from django.shortcuts import render
from django.views.generic import View

# Create your views here.

class ProyectoDjangoIndex(View):
    def get(self, request, *args, **kwargs):
        context={}

        return render(request, 'proyectodjangoindex.html', context)

templates/blog_create.html
<form method="POST">
    {% csrf_token %}
    title{{form.title}}
    <br>
    content{{form.content}}
    <button type="submit">Submit</button>
</form>

templates/blog_delete.html
Está seguro?

<form method="POST">
{% csrf_token %}
{{form}}
<button type="submit">Delete</button>
</form>

templates/blog_detail.html
{{post.title}}
<br>
{{post.content}}

templates/blog_list.html
<a href="{% url 'blog:home' %}">Hola, visita mi blog</a>
<br>
{% for post in posts %}
<a href="{% url 'blog:detail' post.id %}">{{post.title}}</a>
<a href="{% url 'blog:update' post.id %}">Update</a>
<a href="{% url 'blog:delete' post.id %}">Delete</a>
{% endfor %}
<br>
<a href="{% url 'blog:create' %}">Crear un post</a>

templates/blog_update.html
<form method="POST">
    {% csrf_token %}
    title{{form.title}}
    <br>
    content{{form.content}}
    <button type="submit">Update</button>
</form>

templates/index.html
<h1>HOLI DESDE DJANGO JEJEJEJ</h1>

templates/proyectodjangoindex.html
<h1>INDEX PROYECTO DJANGO</h1>